### ISSUE TITLE
Fix Angular internationalization for V3

### ISSUE THREAD

**Issue by DivergentEuropeans** [zowe/zlux#1026]
V2's Angular internationalization is broken. Some brief preliminary research shows us Angular has native variable substitution support, which it didn't last decade when we added a 2nd library to handle Angular i18n. The V3 task appears to be:
- remove 1 of the unneeded libraries
- update existing TranslationLoaderService to use new Angular internationalization implementation
- this likely requires use of Angular CLI

internationalization in React is dev controlled and therefore works perfectly.

```[tasklist]
### Tasks
- [ ] https://github.com/zowe/zlux/issues/1027
- [ ] https://github.com/zowe/zlux/issues/1028
- [ ] https://github.com/zowe/zlux/issues/1029
- [ ] https://github.com/zowe/zlux/issues/1030
```

**Comment by 1000TurquoisePogs** [comment]
Closing as completed in v3.5
