### ISSUE TITLE
Document desktop error codes in v2

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#733]
Put each message of https://github.com/zowe/zlux-app-manager/blob/staging/virtual-desktop/src/assets/i18n/log/messages_en.json 
and 
https://github.com/zowe/zlux-app-manager/blob/staging/bootstrap/src/assets/i18n/log/messages_en.json
into zowe doc site with explanations and suggested user actions for each message.
```[tasklist]
### Tasks
- [ ] https://github.com/zowe/zlux/issues/881
- [ ] https://github.com/zowe/zlux/issues/882
- [ ] https://github.com/zowe/zlux/issues/883
- [ ] https://github.com/zowe/zlux/issues/884
- [ ] https://github.com/zowe/zlux/issues/885
- [ ] https://github.com/zowe/zlux/issues/886
- [ ] https://github.com/zowe/zlux/issues/887
- [ ] https://github.com/zowe/zlux/issues/888
- [ ] https://github.com/zowe/zlux/issues/889
```
