### ISSUE TITLE
Shortcut and folder support for Desktop

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#821]
The result of a recent hackathon was to make folders to group together Desktop plugins, and shortcuts that contain app2app communication data. Together they make the desktop more powerful.

This epic tracks the work that needs to be done to bring that hackathon code to a zowe release.
```[tasklist]
### Tasks
- [ ] https://github.com/zowe/zlux/issues/829
- [ ] https://github.com/zowe/zlux/issues/828
- [ ] https://github.com/zowe/zlux/issues/827
- [ ] https://github.com/zowe/zlux/issues/825
- [ ] https://github.com/zowe/zlux/issues/822
- [ ] https://github.com/zowe/zlux/issues/833
- [ ] https://github.com/zowe/zlux/issues/832
- [ ] https://github.com/zowe/zlux/issues/830
- [ ] https://github.com/zowe/zlux/issues/824
- [ ] https://github.com/zowe/zlux/issues/823
- [ ] https://github.com/zowe/zlux/issues/927
- [ ] https://github.com/zowe/zlux/issues/926
- [ ] https://github.com/zowe/zlux/issues/925
- [ ] https://github.com/zowe/zlux/issues/924
- [ ] https://github.com/zowe/zlux/issues/923
```
