### ISSUE TITLE
Switch tn3270-ng2 to use ts-term

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#869]
https://github.com/zowe/tn3270-ng2 currently uses a [library](https://github.com/zowe/tn3270-ng2/blob/v2.x/staging/webClient/src/lib/js/tn3270.js) of which there is a fork in the OMP at https://github.com/TSTerminal/TSTerm

From that fork, an example of how to use it in the zowe desktop is available at https://github.com/TSTerminal/TSTerm4Zowe

Because this fork looks like it will be easier to maintain our desktop terminal with over time, our first action should be to change "tn3270-ng2" to depend upon "tsterm". After that point, other improvements could be done but perhaps outside the scope of this epic.
```[tasklist]
### Tasks
- [ ] https://github.com/zowe/zlux/issues/959
- [ ] https://github.com/zowe/zlux/issues/957
- [ ] https://github.com/zowe/zlux/issues/956
- [ ] https://github.com/zowe/zlux/issues/958
```

**Comment by Martin-Zeithaml** [comment]
I have a working prototype

## TSTerm
- Added `format iife` and `name org_omp_tsterm_tn3270` to rollup config

## TN3270-ng2
- Added `tsterm` into `package.json`
- Deleted `lib/js/tn3270.js`
- Changed `script-loader` to load from `tsterm`
- Changed variables from `org_zowe_terminal_tn3270` to `org_omp_tsterm_tn3270`

## Quick test
I have changed the [font for terminal in TSTerm](https://github.com/Martin-Zeithaml/TSTerm/blob/6e4342a4d451838ade3a2072bbdc9ab776c11773/src/Generic.ts#L162), build tn3270-ng2 and this is the result:

![image](https://user-images.githubusercontent.com/66114686/214550004-70852c2f-4a81-46f2-894d-dbb8bdb98032.png)

I will use this prototype for #957, #958 and #959.
