### ISSUE TITLE
DB Browser app release

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#870]
There are currently 2 repositories covering a "db browser" app https://github.com/zowe/?q=db-browser&type=all&language=&sort=
They are structured so that you can have plugins for different DB endpoints, like db2, mysql, postgres, whatever is different enough that it needs a distinct plugin to handle its communication.

But apart from that, it's very basic and pretty old right now.
Let's list and work on enhancements we think it needs before putting it in front of end users.
```[tasklist]
### Tasks
- [ ] https://github.com/zowe/zlux/issues/906
- [ ] https://github.com/zowe/zlux/issues/901
- [ ] https://github.com/zowe/zlux/issues/902
- [ ] https://github.com/zowe/zlux/issues/903
```

**Comment by 1000TurquoisePogs** [comment]
Some thoughts on what it might need:

* Update to angular 12 in order to work in zowe v2
* Package as a component in order to be distributed in v2, possibly in an app-store
* Do people like the current UI, or should it change somehow? Themes? Better tables?
* Preference saving: what preferences might people have (such as connections, or table output?)
* Do we allow copying the table contents to clipboard? Do we allow export to a spreadsheet?

**Comment by 1000TurquoisePogs** [comment]
I'm not suggesting we should/shouldnt do certain things, just ideas I had. I'll let @Martin-Zeithaml come up with ideas he'd like to see.
