### ISSUE TITLE
Get CII Best Practices Gold Badge

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zlux#934]
This epic covers items required for CII gold from within our squad.
```[tasklist]
### Tasks
- [ ] https://github.com/zowe/zlux/issues/944
- [ ] https://github.com/zowe/zlux/issues/937
- [ ] https://github.com/zowe/zlux/issues/936
- [ ] https://github.com/zowe/zlux/issues/943
- [ ] https://github.com/zowe/zlux/issues/935
- [ ] https://github.com/zowe/zlux/issues/946
- [ ] https://github.com/zowe/zlux/issues/945
- [ ] https://github.com/zowe/zlux/issues/942
- [ ] https://github.com/zowe/zlux/issues/941
- [ ] https://github.com/zowe/zlux/issues/940
- [ ] https://github.com/zowe/zlux/issues/939
- [ ] https://github.com/zowe/zlux/issues/938
- [ ] https://github.com/zowe/zlux/issues/986
- [ ] https://github.com/zowe/zlux/issues/987
```
